const mongoose = require('mongoose');

const findingSchema = new mongoose.Schema({
  organ: String,              // Esophagus, Stomach-Fundus, etc.
  category: String,           // Inflammatory, Vascular, etc.
  finding: String,            // Specific finding name
  severity: String,           // Grade/Class
  size: String,               // mm/cm
  distance: String,           // Distance from incisors/anus
  location: String,           // Specific location
  count: String,              // For polyps, erosions
  description: String
});

const biopsySchema = new mongoose.Schema({
  taken: { type: Boolean, default: false },
  sites: [String],
  numberOfSamples: Number,
  rut: { type: Boolean, default: false },
  histopathology: { type: Boolean, default: false }
});

const therapeuticSchema = new mongoose.Schema({
  performed: { type: Boolean, default: false },
  // ✅ FIX: Use Mixed type to allow array of objects without casting errors
  procedures: { 
    type: mongoose.Schema.Types.Mixed, 
    default: [] 
  }
});

const complicationSchema = new mongoose.Schema({
  occurred: { type: Boolean, default: false },
  types: [String],
  management: String
});

const reportSchema = new mongoose.Schema({
  reportId: { type: String, unique: true },
  patient: { type: mongoose.Schema.Types.ObjectId, ref: 'Patient', required: true },

  // ✅ NEW METADATA FIELDS
  procedureDate: { type: Date, default: Date.now },
  procedureTime: { type: String, default: () => new Date().toLocaleTimeString('en-US', { hour12: false }) },
  procedureName: { type: String, required: true },
  studyType: { 
    type: String, 
    enum: ['Diagnostic', 'Therapeutic', 'Screening', 'Surveillance'],
    default: 'Diagnostic' 
  },
  indication: String,

  // ✅ SEDATION
  sedation: {
    used: { type: Boolean, default: false },
    type: { type: String, enum: ['Conscious', 'Deep', 'Monitored Anesthesia Care', 'None'] },
    drugName: String,
    dose: String,
    administeredBy: String
  },

  // ✅ CONSENT & ADMIN
  consentObtained: { type: Boolean, default: false },
  consentTime: Date,
  opdIpdNumber: String,
  billNumber: String,
  referringDoctor: String,

  // ✅ DOCTOR INFO
  performingDoctor: {
    name: String,
    qualification: String,
    signature: String
  },
  endoscopist: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  assistant: String,
  nurse: String,

  // ✅ FINDINGS (Structured)
  findings: [findingSchema],
  
  // ✅ ORGAN-SPECIFIC QUICK STATUS
  organStatus: {
    esophagus: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    geJunction: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    stomach: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    duodenum: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    colon: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' }
  },

  // ✅ SPECIAL FINDINGS
  geJunctionDetails: {
    distanceFromIncisors: String,
    hiatusHernia: { type: Boolean, default: false },
    herniaSize: String,
    incompetentLES: { type: Boolean, default: false },
    irregularZLine: { type: Boolean, default: false },
    barrettsEsophagus: { type: Boolean, default: false }
  },

  // ✅ BIOPSY
  biopsy: biopsySchema,

  // ✅ THERAPEUTIC PROCEDURES
  therapeutic: therapeuticSchema,

  // ✅ COMPLICATIONS
  complications: complicationSchema,

  // ✅ SCOPE & EQUIPMENT
  scopeDetails: {
    scopeType: String,
    scopeId: String,
    videoProcessor: String
  },

  // ✅ PROCEDURE QUALITY
  qualityIndicators: {
    bowelPrep: { type: String, enum: ['Excellent', 'Good', 'Fair', 'Poor'] },
    cecumReached: Boolean,
    cecalIntubationTime: String,
    withdrawalTime: String
  },

  // ✅ MEDIA
  images: [{
    filename: String,
    path: String,
    taggedOrgan: String,        // ✅ NEW: Tag to specific organ
    caption: String,
    timestamp: { type: Date, default: Date.now }
  }],

  videos: [{
    filename: String,
    path: String,
    duration: Number,
    uploadedAt: { type: Date, default: Date.now }
  }],

  // ✅ IMPRESSION & RECOMMENDATIONS
  autoGeneratedImpression: String,  // Generated from findings
  customImpression: String,         // Doctor override
  recommendations: String,
  followUp: String,
  comments: String,

  // ✅ REPORT STATUS
  status: { 
    type: String, 
    enum: ['draft', 'finalized', 'amended'], 
    default: 'draft' 
  },
  finalizedAt: Date,
  finalizedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  lastModifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

// Auto-generate Report ID
reportSchema.pre('save', async function(next) {
  if (!this.reportId) {
    const count = await mongoose.model('Report').countDocuments();
    const year = new Date().getFullYear();
    this.reportId = `RPT${year}${String(count + 1).padStart(6, '0')}`;
  }
  next();
});

// ✅ AUTO-GENERATE IMPRESSION FROM FINDINGS
reportSchema.pre('save', function(next) {
  if (this.findings && this.findings.length > 0 && !this.customImpression) {
    const grouped = this.findings.reduce((acc, f) => {
      if (!acc[f.organ]) acc[f.organ] = [];
      acc[f.organ].push(f.finding);
      return acc;
    }, {});
    
    this.autoGeneratedImpression = Object.entries(grouped)
      .map(([organ, findings]) => `${organ}: ${findings.join(', ')}`)
      .join('\n');
  }
  next();
});

module.exports = mongoose.model('Report', reportSchema);