const mongoose = require('mongoose');

const findingSchema = new mongoose.Schema({
  organ: String,
  category: String,
  finding: String,
  severity: String,
  size: String,
  distance: String,
  location: String,
  count: String,
  description: String
});

const biopsySchema = new mongoose.Schema({
  taken: { type: Boolean, default: false },
  sites: [String],
  numberOfSamples: Number,
  rut: { type: Boolean, default: false },
  histopathology: { type: Boolean, default: false }
});

const therapeuticSchema = new mongoose.Schema({
  performed: { type: Boolean, default: false },
  procedures: {
    type: mongoose.Schema.Types.Mixed,
    default: []
  }
});

const complicationSchema = new mongoose.Schema({
  occurred: { type: Boolean, default: false },
  types: [String],
  management: String
});

const imageSchema = new mongoose.Schema({
  filename: String,
  path: String,
  cloudinaryId: String,
  taggedOrgan: String,
  caption: String,
  slotIndex: { type: Number, default: -1 },
  timestamp: { type: Date, default: Date.now }
});

const reportSchema = new mongoose.Schema({
  reportId: { type: String, unique: true },
  patient: { type: mongoose.Schema.Types.ObjectId, ref: 'Patient', required: true },

  procedureDate: { type: Date, default: Date.now },
  procedureTime: { type: String, default: () => new Date().toLocaleTimeString('en-US', { hour12: false }) },
  procedureName: { type: String, required: true },
  studyType: {
    type: String,
    enum: ['Diagnostic', 'Therapeutic', 'Screening', 'Surveillance'],
    default: 'Diagnostic'
  },
  indication: String,

  sedation: {
    used: { type: Boolean, default: false },
    type: { type: String, enum: ['Conscious', 'Deep', 'Monitored Anesthesia Care', 'None'] },
    drugName: String,
    dose: String,
    administeredBy: String
  },

  consentObtained: { type: Boolean, default: false },
  consentTime: Date,
  opdIpdNumber: String,
  billNumber: String,
  referringDoctor: String,

  performingDoctor: {
    name: String,
    qualification: String,
    signature: String
  },
  endoscopist: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  assistant: String,
  nurse: String,

  findings: [findingSchema],

  organStatus: {
    esophagus: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    geJunction: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    stomach: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    duodenum: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' },
    colon: { type: String, enum: ['normal', 'abnormal', 'not_examined'], default: 'normal' }
  },

  geJunctionDetails: {
    distanceFromIncisors: String,
    hiatusHernia: { type: Boolean, default: false },
    herniaSize: String,
    incompetentLES: { type: Boolean, default: false },
    irregularZLine: { type: Boolean, default: false },
    barrettsEsophagus: { type: Boolean, default: false }
  },

  biopsy: biopsySchema,
  therapeutic: therapeuticSchema,
  complications: complicationSchema,

  scopeDetails: {
    scopeType: String,
    scopeId: String,
    videoProcessor: String
  },

  qualityIndicators: {
    bowelPrep: { type: String, enum: ['Excellent', 'Good', 'Fair', 'Poor'] },
    cecumReached: Boolean,
    cecalIntubationTime: String,
    withdrawalTime: String
  },

  images: [imageSchema],
  poolImages: [imageSchema],

  videos: [{
    filename: String,
    path: String,
    cloudinaryId: String,
    size: Number,
    duration: Number,
    uploadedAt: { type: Date, default: Date.now }
  }],

  autoGeneratedImpression: String,
  customImpression: String,
  recommendations: String,
  followUp: String,
  comments: String,

  pdfPath: String,
  pdfGeneratedAt: Date,

  status: {
    type: String,
    enum: ['draft', 'finalized', 'amended'],
    default: 'draft'
  },
  finalizedAt: Date,
  finalizedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  lastModifiedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }
}, { timestamps: true });

// ✅ FIXED: Generate unique reportId using timestamp + random
reportSchema.pre('save', async function (next) {
  if (!this.reportId) {
    const year = new Date().getFullYear();
    
    let reportId;
    let isUnique = false;
    let attempts = 0;
    
    while (!isUnique && attempts < 10) {
      attempts++;
      
      // ✅ Use highest existing reportId + 1 instead of count
      try {
        const lastReport = await mongoose.model('Report')
          .findOne({ reportId: new RegExp(`^RPT${year}`) })
          .sort({ reportId: -1 })
          .select('reportId')
          .lean();

        let nextNumber = 1;
        
        if (lastReport && lastReport.reportId) {
          // Extract number from last reportId e.g. RPT2026000004 -> 4
          const lastNumber = parseInt(lastReport.reportId.replace(`RPT${year}`, ''));
          if (!isNaN(lastNumber)) {
            nextNumber = lastNumber + 1;
          }
        }

        reportId = `RPT${year}${String(nextNumber).padStart(6, '0')}`;

        // ✅ Double check it doesn't exist
        const exists = await mongoose.model('Report')
          .findOne({ reportId })
          .select('_id')
          .lean();

        if (!exists) {
          isUnique = true;
        } else {
          // ✅ If exists, add random suffix and try again
          reportId = `RPT${year}${String(nextNumber + attempts).padStart(6, '0')}`;
          const exists2 = await mongoose.model('Report')
            .findOne({ reportId })
            .select('_id')
            .lean();
          if (!exists2) {
            isUnique = true;
          }
        }
      } catch (e) {
        // ✅ Fallback: use timestamp-based ID
        const timestamp = Date.now().toString().slice(-6);
        reportId = `RPT${year}${timestamp}`;
        isUnique = true;
      }
    }

    // ✅ Final fallback if all attempts fail
    if (!isUnique || !reportId) {
      const timestamp = Date.now().toString().slice(-6);
      const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
      reportId = `RPT${year}T${timestamp}${random}`;
    }

    this.reportId = reportId;
    console.log(`📋 Generated Report ID: ${reportId}`);
  }
  next();
});

// Auto-generate impression
reportSchema.pre('save', function (next) {
  if (this.findings && this.findings.length > 0 && !this.customImpression) {
    const grouped = this.findings.reduce((acc, f) => {
      if (!acc[f.organ]) acc[f.organ] = [];
      acc[f.organ].push(f.finding);
      return acc;
    }, {});

    this.autoGeneratedImpression = Object.entries(grouped)
      .map(([organ, findings]) => `${organ}: ${findings.join(', ')}`)
      .join('\n');
  }
  next();
});

module.exports = mongoose.model('Report', reportSchema);